### ISSUE TITLE
Is this the way to contribute to github?

### ISSUE THREAD

**Issue by Tony363** [kkdai/AMA#1]
I need more “issues” records on my github

**Comment by kkdai** [comment]
Hi Tony
Maybe you would like to specific one repo. 
We could discuss more detail on that repo. 

I quick overview your repos, you may need more work on your Readme file. 

It just like a great banner of the store. 
You need pay attention to decorate it. 

Maybe it is a good start to provide some readme likes:

- How to use
- How to install 
- How to file issue

Also you could file few "good fist issue" first. 

And don't forget to promote it. 
No one will know it until you promote it.

**Comment by Tony363** [comment]
Thanks! It will be another project of mine to upcycle my github repositories! I think it will help my job searches too~
