### ISSUE TITLE
Fork and Clone

### ISSUE THREAD

**Issue by beatriceadel** [kkdai/AMA#2]
Are Forking and Cloning in GitHub the same? If they're not, how do they differ?

**Comment by kkdai** [comment]
Fork:
If you want to copy someone's repo (repository) to your own account. It help you to modify your own version on GitHub. 


Clone: 
If you want to "download" the code from GitHub to your computer. You could use clone to download it. 

But it still under someone's repo and you could not update back GitHub until you send the update request (a.k.a. Pull request). 

Hope it helps.

**Comment by kkdai** [comment]
close it since no feedback for a year.
