### ISSUE TITLE
What is the appropriate course of action when my supervisor is not competent enough to make critical decisions for specific requirements of my recommendation project that caused unnecessary delays and ambiguity?

### ISSUE THREAD

**Issue by Tony363** [kkdai/AMA#6]
I think the most problematic problem for me is that my supervisors and consultants actually dont know what they are doing but always expect me to get their approval first before I proceed with execution. They expect me to “know what they want” , “figure it out” and also get their approval each step of the way. I think that is a very inefficient and ineffective mode of working.

I am used to taking calculated risks and continually churning out results while under a hierarchy of competence. I dislike complacency and I have disdain for unnecessary agreeableness that does not produce results.

Each consultant and supervisor would have different suggestions and all of them are the wrong suggestions for the project in my opinion. How can I direct my project in a way that I can produce results and handle company burreaucracy at the same time?

-Tony

**Comment by Tony363** [comment]
I would also like to ask whether it is a disadvantage for me that I can't read or write chinese going into tech companies in Taiwan? One problem that i faced during building student to university recommendation system was that i actually had no idea what the data meant when scraping the data and had to constantly ask for contextual explanation of the raw data to me by others. I also didn't know how the chinese language worked so it was difficult for me to parse chinese characters or build ERDs for data base architecture.  I solved that problem with my sheer persistency to get results and unrelenting asking of verification from my colleagues and supervisors. My chinese improved alot in the process in terms of my vocabulary. My actual technical skills however, not so much.

**Comment by kkdai** [comment]
1. 
https://github.com/kkdai/AMA/issues/6#issue-990069309

In the question, it is a great example of "technical communication".
Please remember, in the US or Europe if your listener could not get what you want to say. You need to make it simple and easy understand for your supervisor.
   
Try to explain to your supervisor as following in your content.:

- What you want to do (in a simple way), 
- Elaborate your possible results, 
- Elaborate your risk, 
- Roughly Schedule.

Make more than two options and let your boss try to select what you want to do.

**Comment by kkdai** [comment]
2. https://github.com/kkdai/AMA/issues/6#issuecomment-914487695

For the Data Engineering process. Not all data engineers understand the detail of those data.
In that time, we will have one "Data PM" who will understand all the data meaning. 
He/She will help to write down the detailed data spec for ETL.
(e.g.)

- Social security number: F**1**23456789 or A2134456789. the first **F1** means Male lives in New Taipei City and A2 means female lives in Taipei City. 



In your case, try to find someone who could help you to write down the data spec (or Data Document).
It will help you to process those data.
